### ISSUE TITLE
Karafka Web Dashboard - undefined method `delete_if' for nil:NilClass

### ISSUE THREAD

**Issue by alan-sapaad** [karafka/karafka-web#242]
I am getting the error `undefined method 'delete_if' for nil:NilClass` when visiting the status page and the Dashboard page of Karafka. I am having a fresh installation of Karafka web.

Initially, I was getting the 404 page, but when I added the consumer group for karafka-admin, I am getting this error.

Stack trace:

```
NoMethodError (undefined method `delete_if' for nil:NilClass

              state_hash[:processes].delete_if do |_, details|
                                    ^^^^^^^^^^):

karafka-web (0.7.10) lib/karafka/web/ui/models/consumers_state.rb:58:in `evict_expired_processes'
karafka-web (0.7.10) lib/karafka/web/ui/models/consumers_state.rb:27:in `current'
karafka-web (0.7.10) lib/karafka/web/ui/models/consumers_state.rb:37:in `current!'
karafka-web (0.7.10) lib/karafka/web/ui/controllers/dashboard.rb:11:in `index'
karafka-web (0.7.10) lib/karafka/web/ui/app.rb:26:in `block (2 levels) in <class:App>'
```

It looks like the keys of `state_hash` is not symbolized.
The value of `state_hash` on this line is
```
{"processes"=>{}, "stats"=>{"batches"=>0, "messages"=>0, "retries"=>0, "dead"=>0, "busy"=>0, "enqueued"=>0, "processing"=>0, "workers"=>0, "processes"=>0, "rss"=>0, "listeners"=>0, "utilization"=>0, "lag_stored"=>0, "errors"=>0}, "schema_state"=>"accepted", "schema_version"=>"1.1.0", "dispatched_at"=>1704169468.4562628}
```

## Expected behavior

The web Dashboard should load when I visit `/karafka/dashboard`
The status page should load when I visit `/karafka/status`

## Actual behavior

I'm getting the above mentioned error

## Steps to reproduce the problem

Just visiting the karafka/dashboard is triggering this error

## Your setup details
```
bundle exec karafka info

@@@                                             @@@@@  @@@
@@@                                            @@@     @@@
@@@  @@@    @@@@@@@@@   @@@ @@@   @@@@@@@@@  @@@@@@@@  @@@  @@@@   @@@@@@@@@
@@@@@@     @@@    @@@   @@@@@    @@@    @@@    @@@     @@@@@@@    @@@    @@@
@@@@@@@    @@@    @@@   @@@     @@@@    @@@    @@@     @@@@@@@    @@@    @@@
@@@  @@@@  @@@@@@@@@@   @@@      @@@@@@@@@@    @@@     @@@  @@@@   @@@@@@@@@@


Karafka version: 2.2.14
Ruby version: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]
Rdkafka version: 0.14.7
Consumer groups count: 2
Subscription groups count: 2
Workers count: 5
Application client id: events-broker
Boot file: /Users/***/***/***/karafka-web/karafka.rb
Environment: development
License: LGPL-3.0
Shutting down Waterdrop producers...
[2ab8f9a489c3] Closing producer took 0.015000343322753906 ms
```

Thanks!

**Comment by mensfeld** [comment]
:wave: web-ui should use a custom deserializer. Can you show me your `karafka.rb`?

**Comment by mensfeld** [comment]
@alan-sapaad also, what does the `karafka/status` page displays?

**Comment by alan-sapaad** [comment]
Hi @mensfeld!
`karafka/status` page triggers the same error mentioned above. (`undefined method 'delete_if' for nil:NilClass`)

Hey, I got it working, It was a typo from my end. In the `karafka.rb` file, I had this:

```
routes.draw do
    consumer_group 'events-monitor' do
      topic "#{ENV['KAFKA_PREFIX']}acks" do consumer EventsConsumer  end
    end
end
```

It worked when I added a new line after `do`.
```
routes.draw do
    consumer_group 'events-monitor' do
      topic "#{ENV['KAFKA_PREFIX']}acks" do
          consumer EventsConsumer 
       end
    end
end
```

Thank you for your time!
I'm closing this issue.

**Comment by mensfeld** [comment]
@alan-sapaad  glad it worked. As a sidenote: the web UI should **not** be mounted that way. All web UI setup should be done through web-ui configuration.

**Comment by alan-sapaad** [comment]
@mensfeld I did not get you.
Could you please advice on this setup:
I have a microservice architecture. I want to host the Karafka Web as a dedicated rails app, where I need to log all events as well.

To achieve this, in one of the microservices, I have this:
```
# karafka

# frozen_string_literal: true

class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka = {
      'security.protocol': 'ssl',
      'bootstrap.servers': ENV['KAFKA_URL'].gsub('kafka+ssl://', ''),
      'ssl.certificate.pem': ENV['KAFKA_CLIENT_CERT'],
      'ssl.key.pem': ENV['KAFKA_CLIENT_CERT_KEY'],
      'ssl.ca.pem': ENV['KAFKA_TRUSTED_CERT'],
      'ssl.endpoint.identification.algorithm': 'none',
      'allow.auto.create.topics': false,
      'partition.assignment.strategy': 'cooperative-sticky',
      'topic.metadata.refresh.interval.ms': 5 * 60 * 1_000
    }

    config.client_id = 'microservice-a'
    config.consumer_persistence = !Rails.env.development?
    config.initial_offset = 'latest'

    config.strict_topics_namespacing = false

    config.consumer_mapper = ->(raw_group_name) { "#{ENV['KAFKA_PREFIX']}#{raw_group_name}" }
  end

  Karafka.producer.monitor.subscribe(
    WaterDrop::Instrumentation::LoggerListener.new(
      # Log producer operations using the Karafka logger
      Karafka.logger,
      # If you set this to true, logs will contain each message details
      # Please note, that this can be extensive
      log_messages: false
    )
  )

  routes.draw do
    consumer_group "microservice-a" do
      topic "#{ENV['KAFKA_PREFIX']}order_events" do
        consumer EventsConsumer
      end

      topic "#{ENV['KAFKA_PREFIX']}cart_events" do
        consumer EventsConsumer
      end
    end
  end
end

::Karafka.producer.monitor.subscribe('error.occurred') do |event|
  case event[:type]
  # Every single message that received a handler is delivered or fails event
  when 'librdkafka.dispatch_error'
    puts "KafkaClient:ERROR:: Message with label: #{event[:delivery_report].label} failed to be delivered"
  else
    # Track all the others
    puts "KafkaClient:ERROR:: Message failed to be delivered | error_event: #{event}"
  end
end

Karafka::Web.setup do |config|
  config.topics.errors = "#{ENV['KAFKA_PREFIX']}karafka_errors"
  config.topics.consumers.metrics = "#{ENV['KAFKA_PREFIX']}karafka_consumers_metrics"
  config.topics.consumers.reports = "#{ENV['KAFKA_PREFIX']}karafka_consumers_reports"
  config.topics.consumers.states = "#{ENV['KAFKA_PREFIX']}karafka_consumers_states"

  config.processing.active = false
end

Karafka::Process.tags.add(:application_name, 'microservice_a')

Karafka::Web.enable!

at_exit do
  puts 'Shutting down Waterdrop producers...'
  ::Karafka.producer.close
end
```
Note that I've set the `config.processing.active` to `false`

And in the dedicated Karafka web rails app, the only change is
```
config.processing.active = true
```

In both the apps, I am running `karafka server`

In the Karafka web rails app's status page, I am seeing this error:
`There are no Karafka consumer processes actively reporting to the Web UI.`

What am I missing?
thanks!

**Comment by mensfeld** [comment]
@alan-sapaad would you mind joining our slack channel? http://slack.karafka.io/ it is much better for this type of support and we can post final solution here as well for general audience to reference. WDYT?

**Comment by alan-sapaad** [comment]
Sure!

**Comment by mensfeld** [comment]
For anyone reading: the issue was not having consumer group for admin and web-ui created. This has been resolved and docs have been updated: https://karafka.io/docs/Deployment/#heroku-kafka-prefix-convention
