### ISSUE TITLE
karafka server cannot start due to dependency loading on karafka-web 0.8.2

### ISSUE THREAD

**Issue by coneybeare** [karafka/karafka-web#440]
First and foremost, thanks for an incredible set of kafka tooling! I have a legacy project still stuck on ruby 2.7.7 (🤞 we can update soon) which means I am stuck on `karafka v2.3.4` and `karafka-web v0.8.2` for the time being. 

I am able to install both gems using basic config, and install/mount/run the web ui on my rails app without problems.

When I go to start a server for consuming topics however, I am getting a dependency loading error that is unexpected, considering that both `karafka` and `karafka-web` are installed and working fine.

I know that both of these are older and not going to get any updates, so I guess I am looking to see if I am missing something obvious in the setup, or if this is indeed and issue I will have to fork the package to fix.
--------

## Expected behavior

I would expect the `bundle exec karakfa server` command to work as documented.

## Actual behavior

The `server` command fails on load with the following stack trace

```
$ bin/test_run bundle exec karafka server

[...] # docker container launch/setup output

bundler: failed to load command: karafka (/usr/local/bundle/bin/karafka)
LoadError: cannot load such file -- /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/tracking
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/config.rb:61:in `block in <class:Config>'
  /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/configurable/node.rb:25:in `instance_eval'
  /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/configurable/node.rb:25:in `initialize'
  /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/configurable/node.rb:37:in `new'
  /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/configurable/node.rb:37:in `setting'
  /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/configurable.rb:71:in `setting'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/config.rb:48:in `<class:Config>'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/config.rb:6:in `<module:Web>'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/config.rb:4:in `<module:Karafka>'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/config.rb:3:in `<main>'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/cref.rb:91:in `const_get'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/cref.rb:91:in `get'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:173:in `block in actual_eager_load_dir'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/helpers.rb:47:in `block in ls'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/helpers.rb:25:in `each'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/helpers.rb:25:in `ls'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:168:in `actual_eager_load_dir'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:16:in `each'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web.rb:76:in `<main>'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:88:in `require'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:88:in `rescue in block in require'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:65:in `block in require'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
  /usr/local/lib/ruby/2.7.0/bundler.rb:174:in `require'
  /redacted/config/application.rb:12:in `<top (required)>'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
  /redacted/config/environment.rb:4:in `<top (required)>'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
  /usr/local/bundle/gems/karafka-2.3.4/lib/karafka/cli/base.rb:52:in `load'
  /usr/local/bundle/gems/karafka-2.3.4/bin/karafka:9:in `<top (required)>'
  /usr/local/bundle/bin/karafka:23:in `load'
  /usr/local/bundle/bin/karafka:23:in `<top (required)>'
```

The line in the project code that kicks this off  (`environment.rb`) is simply the bundler require line.

```
Bundler.require(*Rails.groups.append(:console))
```

## Steps to reproduce the problem

ruby: 2.7.7
rails: 5.2.8.1
karafka: 2.3.4
karafka-web: 0.8.2
 
## Your setup details

Please provide kafka version and the output of `karafka info` or `bundle exec karafka info` if using Bundler.

`bundle exec karafka info` gives the same stack trace above

**Comment by coneybeare** [comment]
Line 61 of the config file in v 0.8.2 is 

```
        # Main Web UI reporting scheduler that runs a background thread and reports periodically
        # from the consumer reporter and producer reporter
        setting :scheduler, default: Tracking::Scheduler.new
```

**Comment by coneybeare** [comment]
After adding `loader.log!` to the `web.rb` file, I see some additional info 

```
bash-5.1# bundle exec karafka info
Install `ransack` gem before using `JSONAPI::Filtering`!
Zeitwerk@karafka-web: eager load start
Zeitwerk@karafka-web: eager load directory /usr/local/bundle/gems/karafka-web-0.8.2/lib start
Zeitwerk@karafka-web: autoload set for Karafka::Web::Cli::Base, to be loaded from /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/cli/base.rb
Zeitwerk@karafka-web: autoload set for Karafka::Web::Cli::Help, to be loaded from /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/cli/help.rb
Zeitwerk@karafka-web: autoload set for Karafka::Web::Cli::Install, to be loaded from /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/cli/install.rb
Zeitwerk@karafka-web: autoload set for Karafka::Web::Cli::Migrate, to be loaded from /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/cli/migrate.rb
Zeitwerk@karafka-web: autoload set for Karafka::Web::Cli::Reset, to be loaded from /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/cli/reset.rb
Zeitwerk@karafka-web: autoload set for Karafka::Web::Cli::Uninstall, to be loaded from /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/cli/uninstall.rb
bundler: failed to load command: karafka (/usr/local/bundle/bin/karafka)
LoadError: cannot load such file -- /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/tracking
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/config.rb:61:in `block in <class:Config>'
  /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/configurable/node.rb:25:in `instance_eval'
  /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/configurable/node.rb:25:in `initialize'
  /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/configurable/node.rb:37:in `new'
  /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/configurable/node.rb:37:in `setting'
  /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/configurable.rb:71:in `setting'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/config.rb:48:in `<class:Config>'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/config.rb:6:in `<module:Web>'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/config.rb:4:in `<module:Karafka>'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web/config.rb:3:in `<main>'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
  /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/cref.rb:91:in `const_get'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/cref.rb:91:in `get'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:173:in `block in actual_eager_load_dir'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/helpers.rb:47:in `block in ls'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/helpers.rb:25:in `each'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/helpers.rb:25:in `ls'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:168:in `actual_eager_load_dir'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:16:in `each'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
  /usr/local/bundle/gems/karafka-web-0.8.2/lib/karafka/web.rb:77:in `<main>'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:88:in `require'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:88:in `rescue in block in require'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:65:in `block in require'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
  /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
  /usr/local/lib/ruby/2.7.0/bundler.rb:174:in `require'
  /redacted/config/application.rb:12:in `<top (required)>'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
  /redacted/config/environment.rb:4:in `<top (required)>'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
  /usr/local/bundle/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
  /usr/local/bundle/gems/karafka-2.3.4/lib/karafka/cli/base.rb:52:in `load'
  /usr/local/bundle/gems/karafka-2.3.4/bin/karafka:9:in `<top (required)>'
  /usr/local/bundle/bin/karafka:23:in `load'
  /usr/local/bundle/bin/karafka:23:in `<top (required)>'
bash-5.1#
```

**Comment by mensfeld** [comment]
Hey,

1. All of stuff you are doing is not supported due to EOLs: https://karafka.io/docs/Versions-Lifecycle-and-EOL/

2. If your busyness relies on my software to a degree that you are investing hours on debugging, please consider supporting me.

3. Next time please look into the FAQ:

https://karafka.io/docs/FAQ/#why-am-i-experiencing-a-load-error-when-using-karafka-with-ruby-27-and-how-can-i-fix-it

**Comment by coneybeare** [comment]
1. I know, upgrading the main applications and addressing tech debt is a top priority
2. Of course
3. I did look there, but my grepping missed this. Thank you for the link!

**Comment by mensfeld** [comment]
1. FYI 3.0 is EOL as well (the Ruby language) and Karafka drops its support from the ecosystem in two weeks.
2. Thank you. Without support I may not be able to move this ecosystem forward so if you're doing serious stuff with Karafka, help is highly appreciated
3. No problem. It happens. Please ping me if it worked (it should).
